id: Provodor

version: 0.1.0
author: Cyclic


addons:
  biome-provider-pipeline: "1.+"
  biome-provider-single: "1.+"
  biome-provider-extrusion: "1.+"
  chunk-generator-noise-3d: "1.+"
  config-biome: "1.+"
  config-flora: "1.+"
  config-noise-function: "1.+"
  config-ore: "1.+"
  config-palette: "1.+"
  config-distributors: "1.+"
  config-locators: "1.+"
  config-feature: "1.+"
  structure-terrascript-loader: "1.+"
  structure-sponge-loader: "1.+"
  language-yaml: "1.+"
  generation-stage-feature: "1.+"
  structure-function-check-noise-3d: "1.+"
  palette-block-shortcut: "1.+"
  structure-block-shortcut: "1.+"
  terrascript-function-sampler: "1.+"
stages:
  - id: landforms
    type: FEATURE
  - id: trees
    type: FEATURE
  - id: flora
    type: FEATURE
  - id: ores
    type: FEATURE

biomes: $Settings.yml:BiomePool
stages:
  - type: REPLACE
    from: overworld
    to: $Settings.yml:BiomePool
    sampler:
      dimensions: 2
      type: CELLULAR
      return: CellValue
      salt: 69420101
      frequency: 0.03
  - type: FRACTAL_EXPAND
    sampler:
      type: WHITE_NOISE
  - type: FRACTAL_EXPAND
    sampler:
      type: WHITE_NOISE
  - type: FRACTAL_EXPAND
    sampler:
      type: WHITE_NOISE
  - type: SMOOTH
    sampler:
      type: WHITE_NOISE
  - type: SMOOTH
    sampler:
      type: WHITE_NOISE
  - type: SMOOTH
    sampler:
      type: WHITE_NOISE
  - type: SMOOTH
    sampler:
      type: WHITE_NOISE
  - type: SMOOTH
    sampler:
      type: WHITE_NOISE
  - type: SMOOTH
    sampler:
      type: WHITE_NOISE
  - type: SMOOTH
    sampler:
      type: WHITE_NOISE
generator: NOISE_3D